* Encoding: UTF-8.

EXAMINE VARIABLES=Project_Loss BY Most_Effective
  /PLOT NPPLOT
  /STATISTICS DESCRIPTIVES
  /CINTERVAL 95
  /MISSING LISTWISE
  /NOTOTAL.

EXAMINE VARIABLES=Project_Loss
  /PLOT NONE
  /STATISTICS DESCRIPTIVES
  /CINTERVAL 95
  /MISSING LISTWISE
  /NOTOTAL.

NPAR TESTS
  /K-W=Project_Loss BY Most_Effective(1 3)
  /MISSING ANALYSIS.

