* Encoding: UTF-8.

FREQUENCIES VARIABLES=MostEffective
  /ORDER=ANALYSIS.

NPAR TESTS
  /CHISQUARE=MostEffective
  /EXPECTED=EQUAL
  /MISSING ANALYSIS.

FREQUENCIES VARIABLES=MostEffective_Prog
  /ORDER=ANALYSIS.

NPAR TESTS
  /CHISQUARE=MostEffective_Prog
  /EXPECTED=EQUAL
  /MISSING ANALYSIS.

