* Encoding: UTF-8.

FREQUENCIES VARIABLES=Easiest_Prog
  /ORDER=ANALYSIS.

NPAR TESTS
  /CHISQUARE=Easiest_Prog
  /EXPECTED=EQUAL
  /MISSING ANALYSIS.

FREQUENCIES VARIABLES=BestApplied Preferred EasyApply
  /ORDER=ANALYSIS.

NPAR TESTS
  /CHISQUARE=BestApplied Preferred EasyApply
  /EXPECTED=EQUAL
  /MISSING ANALYSIS.

