* Encoding: UTF-8.

CROSSTABS
  /TABLES=BestApplied BY BestApplied_Real
  /FORMAT=NOTABLES
  /STATISTICS=MCNEMAR
  /COUNT ROUND CELL.


CROSSTABS
  /TABLES=Preferred BY Preferred_Real
  /FORMAT=NOTABLES
  /STATISTICS=MCNEMAR
  /COUNT ROUND CELL.


CROSSTABS
  /TABLES=EasyApply BY EasyApply_Real
  /FORMAT=NOTABLES
  /STATISTICS=MCNEMAR
  /COUNT ROUND CELL.


CROSSTABS
  /TABLES=Easiest_Prog BY Easiest_Real
  /FORMAT=NOTABLES
  /STATISTICS=MCNEMAR
  /COUNT ROUND CELL.
