* Encoding: UTF-8.

CROSSTABS
  /TABLES=Preferred BY MostEffective
  /FORMAT=NOTABLES
  /STATISTICS=MCNEMAR
  /COUNT ROUND CELL.

CROSSTABS
  /TABLES=EasyApply BY MostEffective
  /FORMAT=NOTABLES
  /STATISTICS=MCNEMAR
  /COUNT ROUND CELL.

CROSSTABS
  /TABLES=Easiest_Prog BY MostEffective_Prog
  /FORMAT=NOTABLES
  /STATISTICS=MCNEMAR
  /COUNT ROUND CELL.

